### ISSUE TITLE
Add support for properties

### ISSUE THREAD

**Issue by JordanSussman** [jmccann/drone-artifactory#3]
Ideally this plugin would add default [Artifactory properties](https://www.jfrog.com/confluence/display/RTF/Properties) like `$DRONE_COMMIT_SHA`, `$DRONE_REPO_LINK`, and `$DRONE_BUILD_NUMBER`. Also, allowing customizable user properties would be a great functionality. 

Modeling it a bit after https://github.com/drone-plugins/drone-docker/pull/180 probably makes sense.

**Comment by jmccann** [comment]
There is a `set-prop` action now to do such a thing.
